name: task_manager_app
description: "Task manager app practice"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #--this package for show svg picture and icon -----
  flutter_svg: ^2.2.1
  #----this package for otp verify ---------
  pin_code_fields: ^8.0.1
  #this package for image pick
  image_picker: ^1.2.0
  #-this package console data spacial vabe show korte---------
  logger: ^2.6.1
  #------------this package for api call ------------
  http: ^1.5.0
  #------------------this package for small data cache e store korte -------
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0
  flutter_native_splash: ^2.4.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/splash/
    - assets/screenshots/
#--- Flutter app icon configure kora ---------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

#--- splash logo configure kora
flutter_native_splash:
  android: true
  ios: true
 # color: "#ffffff"
  background_image: "assets/splash/background.png"
  image: "assets/icons/app_icon.png"
  android_gravity: center
  android_12:
    image: "assets/icons/app_icon.png"
    background_image: "assets/splash/background.png"
    color: "#ffffff"





